// KYC document storage (Phase C §3, PII). Documents live in a PRIVATE Supabase Storage bucket —
// never a public URL. Access is server-authorized (owner or admin) and served via short-lived signed
// URLs generated by the service-role client. The DB stores only the AES-256-GCM-encrypted object
// path (Kyc.{address,pan,bank}DocEnc), so a DB leak alone never reveals a fetchable location.
//
// The pure parts (kinds, path shape, access rule) are unit-testable; the impure parts wrap the
// service-role storage client. The bucket is created private on first use (idempotent).
import { createSupabaseAdminClient } from "../supabase/admin";

export const KYC_BUCKET = "kyc-docs"; // PRIVATE — created with public:false
export const KYC_DOC_KINDS = ["address", "pan", "bank"] as const;
export type KycDocKind = (typeof KYC_DOC_KINDS)[number];

export function isKycDocKind(v: string): v is KycDocKind {
  return (KYC_DOC_KINDS as readonly string[]).includes(v);
}

/** Which encrypted-path column on Kyc backs each doc kind. */
export const KYC_DOC_COLUMN: Record<
  KycDocKind,
  "addressDocEnc" | "panDocEnc" | "bankDocEnc"
> = {
  address: "addressDocEnc",
  pan: "panDocEnc",
  bank: "bankDocEnc",
};

/** Object path inside the bucket. `rand` is injected so the pure shape is testable. */
export function kycDocPath(
  userId: string,
  kind: KycDocKind,
  ext: string,
  rand: string,
): string {
  const safeExt =
    ext
      .replace(/[^a-z0-9]/gi, "")
      .toLowerCase()
      .slice(0, 5) || "bin";
  return `${userId}/${kind}/${rand}.${safeExt}`;
}

/**
 * PURE authorization rule: only the owner or an admin may access a KYC document. The requester's
 * ownership/role is resolved by the caller (server) — this never trusts client input.
 */
export function canAccessKycDoc(input: {
  requesterId: string | null;
  ownerId: string;
  isAdmin: boolean;
}): boolean {
  if (input.isAdmin) return true;
  return input.requesterId != null && input.requesterId === input.ownerId;
}

const ALLOWED_CONTENT = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "application/pdf",
]);
export function isAllowedDocContentType(ct: string): boolean {
  return ALLOWED_CONTENT.has(ct);
}

/** Create the private bucket if missing. Idempotent; safe to call before each upload. */
export async function ensureKycBucket(): Promise<void> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin.storage.getBucket(KYC_BUCKET);
  if (data) return;
  const { error } = await admin.storage.createBucket(KYC_BUCKET, {
    public: false,
  });
  // A concurrent create races to "already exists" — treat that as success.
  if (error && !/exist/i.test(error.message))
    throw new Error(`KYC bucket: ${error.message}`);
}

/** Upload a document to the private bucket. Returns the object path (to be encrypted before storing). */
export async function uploadKycDoc(input: {
  userId: string;
  kind: KycDocKind;
  bytes: ArrayBuffer | Uint8Array;
  contentType: string;
  ext: string;
  rand: string;
}): Promise<string> {
  await ensureKycBucket();
  const admin = createSupabaseAdminClient();
  const path = kycDocPath(input.userId, input.kind, input.ext, input.rand);
  const { error } = await admin.storage
    .from(KYC_BUCKET)
    .upload(path, input.bytes, {
      contentType: input.contentType,
      upsert: true,
    });
  if (error) throw new Error(`KYC upload failed: ${error.message}`);
  return path;
}

/** Short-lived signed URL for a private object (default 60s). Callers MUST authorize first. */
export async function kycDocSignedUrl(
  path: string,
  expiresInSec = 60,
): Promise<string> {
  const admin = createSupabaseAdminClient();
  const { data, error } = await admin.storage
    .from(KYC_BUCKET)
    .createSignedUrl(path, expiresInSec);
  if (error || !data?.signedUrl)
    throw new Error(`KYC signed URL failed: ${error?.message ?? "unknown"}`);
  return data.signedUrl;
}
