// QA-01 report generator. Reads docs/qa/QA-01/results.json (from the capture spec) and produces:
//   • docs/qa/QA-01/index.md — the mechanical pass/fail matrix vs DESIGN_DIRECTION v1.0 budgets;
//   • an auto-maintained block of PRODUCT_DEBT.md rows for BROKEN states (hard budget misses),
//     regenerated in place between markers so re-runs never duplicate and manual rows are untouched.
//
// Mechanical only — NO UX opinions. A "hard fail" is an objective, non-advisory budget miss
// (broken render / horizontal overflow / CLS). Dev-server LCP and tap-target checks are ADVISORY
// (dev builds are unoptimised; inline controls legitimately vary) → surfaced in the index, never
// auto-filed as debt.
//
//   npx tsx scripts/qa-report.ts
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { THRESHOLDS, scoreBudgets, type BudgetLine } from "../e2e/qa/budgets";
import { ROUTES } from "../e2e/qa/routes";
import {
  RESULTS_JSON,
  OUT_DIR,
  type ShotResult,
  type RunManifest,
} from "../e2e/qa/results";

const routeMeta = new Map(ROUTES.map((r) => [r.id, r]));

const PRODUCT_DEBT = resolve(process.cwd(), "docs", "PRODUCT_DEBT.md");
const INDEX_MD = resolve(OUT_DIR, "index.md");
const AUTO_START =
  "<!-- QA-01:AUTO:START — regenerated by scripts/qa-report.ts, do not edit by hand -->";
const AUTO_END = "<!-- QA-01:AUTO:END -->";

// Budgets that are HARD (a miss = broken / debt) vs ADVISORY (reported, never auto-filed).
const HARD_KEYS = new Set(["http", "console", "pageerror", "overflow", "cls"]);

if (!existsSync(RESULTS_JSON)) {
  throw new Error(`No results at ${RESULTS_JSON}. Run the capture spec first.`);
}
const run: RunManifest = JSON.parse(readFileSync(RESULTS_JSON, "utf8"));

// Re-score budgets HERE from the raw recorded facts (metrics + final console/pageerror/http), rather
// than trusting the spec's stored r.budgets: console/pageerror events can arrive after the spec
// scored them, so the report is the single source of truth for verdicts.
function budgetsFor(r: ShotResult): BudgetLine[] {
  if (r.status !== "captured" || !r.metrics) return [];
  return scoreBudgets(r.metrics, THRESHOLDS, {
    httpOk: r.httpOk,
    httpStatus: r.httpStatus ?? 0,
    consoleErrors: r.consoleErrors,
    pageError: r.pageError,
  });
}

type Verdict = "PASS" | "ADVISORY" | "FAIL" | "SKIP" | "ERROR";
function verdictFor(r: ShotResult): Verdict {
  if (r.status === "skipped") return "SKIP";
  if (r.status === "error") return "ERROR";
  const budgets = budgetsFor(r);
  const hard = budgets.some(
    (b) => HARD_KEYS.has(b.key) && b.verdict === "fail",
  );
  if (hard) return "FAIL";
  const adv = budgets.some((b) => b.verdict === "advisory-fail");
  return adv ? "ADVISORY" : "PASS";
}
const VERDICT_BADGE: Record<Verdict, string> = {
  PASS: "✅ PASS",
  ADVISORY: "🟡 ADV",
  FAIL: "❌ FAIL",
  SKIP: "⏭️ SKIP",
  ERROR: "💥 ERR",
};

function cell(r: ShotResult): string {
  const v = verdictFor(r);
  if (r.status !== "captured") return VERDICT_BADGE[v];
  return `[${VERDICT_BADGE[v]}](${r.screenshot})`;
}

function budgetSummary(r: ShotResult): string {
  if (r.status !== "captured" || !r.metrics)
    return r.skipReason ?? r.pageError ?? "—";
  const m = r.metrics;
  const bits = [
    `ovf ${m.horizontalOverflowPx}px`,
    `CLS ${m.cls.toFixed(3)}`,
    `LCP ${m.lcpMs === null ? "n/a" : m.lcpMs + "ms"}`,
    `tap ${m.undersizedTapTargets}`,
  ];
  if (r.consoleErrors) bits.push(`**${r.consoleErrors} console err**`);
  if (r.pageError) bits.push(`**pageerror**`);
  if (r.redirected)
    bits.push(`↪ ${r.finalUrl ? new URL(r.finalUrl).pathname : "?"}`);
  return bits.join(" · ");
}

// ── Aggregate counts ───────────────────────────────────────────────────────────────────────────
const byVerdict: Record<Verdict, number> = {
  PASS: 0,
  ADVISORY: 0,
  FAIL: 0,
  SKIP: 0,
  ERROR: 0,
};
for (const r of run.results) byVerdict[verdictFor(r)]++;
const captured = run.results.filter((r) => r.status === "captured");

// Per-budget pass counts (captured shots only).
const budgetKeys = [
  "http",
  "console",
  "pageerror",
  "overflow",
  "cls",
  "lcp",
  "tap",
] as const;
const budgetLabel: Record<string, string> = {
  http: "HTTP status ok",
  console: "No console errors",
  pageerror: "No uncaught error",
  overflow: "No H-overflow (§6/§18)",
  cls: "CLS ≤ 0.1 (§10/§17)",
  lcp: "LCP < 2.5s (§6/§17, advisory)",
  tap: "Tap ≥44px (§18, advisory)",
};
function budgetStats(key: string): {
  pass: number;
  total: number;
  fails: ShotResult[];
} {
  let pass = 0;
  const fails: ShotResult[] = [];
  for (const r of captured) {
    const b = budgetsFor(r).find((x) => x.key === key);
    if (!b || b.verdict === "n/a") continue;
    if (b.verdict === "pass") pass++;
    else fails.push(r);
  }
  return { pass, total: pass + fails.length, fails };
}

// ── Build the index ─────────────────────────────────────────────────────────────────────────────
const routeIds = [...new Set(run.results.map((r) => r.routeId))];
const lines: string[] = [];
lines.push("# QA-01 — Screenshot & Budget Harness");
lines.push("");
lines.push(
  `> Mechanical capture of **every route** at **360 / 768 / 1280px** in each reachable state ` +
    `(default · empty · loading · error), scored against the objective **DESIGN_DIRECTION v1.0** ` +
    `budgets. **No UX opinions** — this harness measures numbers only; subjective quality is out of scope.`,
);
lines.push("");
lines.push(`- **Generated:** ${run.generatedAt}`);
lines.push(
  `- **Target:** ${run.baseURL} (Next dev server — see LCP caveat below)`,
);
lines.push(
  `- **Sessions:** public (none) · learner (\`qa-learner@goskilledqa.com\`) · admin (\`qa-admin@goskilledqa.com\`, role minted via SQL) — see \`scripts/qa-auth-bootstrap.ts\`.`,
);
lines.push(
  `- **Fixtures:** ` +
    Object.entries(run.fixtures)
      .map(([k, v]) => `${k}=\`${v ?? "∅"}\``)
      .join(" · "),
);
lines.push("");
lines.push("## Result summary");
lines.push("");
lines.push(`| ✅ PASS | 🟡 ADVISORY | ❌ FAIL | ⏭️ SKIP | 💥 ERROR | Total |`);
lines.push(`|---|---|---|---|---|---|`);
lines.push(
  `| ${byVerdict.PASS} | ${byVerdict.ADVISORY} | ${byVerdict.FAIL} | ${byVerdict.SKIP} | ${byVerdict.ERROR} | ${run.results.length} |`,
);
lines.push("");
lines.push(
  "**FAIL** = a hard budget miss (broken render, horizontal overflow, or CLS) → filed to PRODUCT_DEBT.",
);
lines.push(
  "**ADVISORY** = only dev-LCP or tap-target below budget (see caveats) — reported, not filed.",
);
lines.push("");

lines.push("## Budgets & thresholds");
lines.push("");
lines.push("| Budget | Threshold | Kind | Pass rate (captured) |");
lines.push("|---|---|---|---|");
const thresholdText: Record<string, string> = {
  http: "status < 400 (error states < 500)",
  console: "0 errors",
  pageerror: "none",
  overflow: `≤ ${THRESHOLDS.horizontalOverflowPx}px`,
  cls: `≤ ${THRESHOLDS.cls}`,
  lcp: `< ${THRESHOLDS.lcpMs}ms`,
  tap: `≥ ${THRESHOLDS.tapTargetPx}px`,
};
for (const key of budgetKeys) {
  const kind = HARD_KEYS.has(key) ? "hard" : "advisory";
  const s = budgetStats(key);
  lines.push(
    `| ${budgetLabel[key]} | ${thresholdText[key]} | ${kind} | ${s.pass}/${s.total} |`,
  );
}
lines.push("");
lines.push(
  "> **LCP caveat:** measured on the **Next dev server** (unminified, on-demand compiled, source maps) — " +
    "these numbers run far above production and are **advisory only**, never a hard fail. A production-build " +
    "LCP pass is a separate ticket. **Tap-target caveat:** applied to unambiguous controls (`<button>`, " +
    "`[role=button]`, button-classed anchors); inline text links are excluded, so a small count is expected. " +
    "**CLS caveat:** dev-server font swaps + on-demand compile can *over-report* layout shift and it varies " +
    "slightly run-to-run, so a borderline CLS (~0.1–0.2) is indicative — confirm against a production build " +
    "before treating it as fixed. Horizontal-overflow is deterministic and not subject to this caveat.",
);
lines.push("");

// ── Per-route matrix ─────────────────────────────────────────────────────────────────────────
lines.push("## Route matrix");
lines.push("");
lines.push(
  "Each cell links to the full-page screenshot. Columns are the three widths; rows group by route → state.",
);
lines.push("");
lines.push(
  "**State coverage:** `default` is the normal render. A `default (=empty)` label means the fresh QA " +
    "learner account has no data there, so the default shot **is** the genuine empty state (nothing " +
    "fabricated — DR-029). `loading` shots capture the real `loading.tsx` skeleton under network throttle. " +
    "`error` shots hit a deliberately invalid param (not-found / invalid state).",
);
lines.push("");
lines.push(
  "| Route | Auth | Register | State | 360px | 768px | 1280px | Measurements (1280) |",
);
lines.push("|---|---|---|---|---|---|---|---|");
for (const id of routeIds) {
  const rows = run.results.filter((r) => r.routeId === id);
  const states = [...new Set(rows.map((r) => r.state))];
  const meta = rows[0];
  for (const state of states) {
    const w360 = rows.find((r) => r.state === state && r.width === 360);
    const w768 = rows.find((r) => r.state === state && r.width === 768);
    const w1280 = rows.find((r) => r.state === state && r.width === 1280);
    const path = (w1280 ?? w360)?.path ?? meta.path;
    const def = routeMeta.get(id);
    const stateLabel =
      state === "default" && def?.defaultIsEmpty ? "default (=empty)" : state;
    lines.push(
      `| \`${id}\`<br><sub>${path}</sub> | ${meta.auth} | ${meta.register} | ${stateLabel} | ` +
        `${w360 ? cell(w360) : "—"} | ${w768 ? cell(w768) : "—"} | ${w1280 ? cell(w1280) : "—"} | ` +
        `${w1280 ? budgetSummary(w1280) : "—"} |`,
    );
  }
}
lines.push("");

// ── Broken states + skips ────────────────────────────────────────────────────────────────────
const fails = run.results.filter(
  (r) => verdictFor(r) === "FAIL" || verdictFor(r) === "ERROR",
);
lines.push("## Broken states (→ PRODUCT_DEBT.md)");
lines.push("");
if (fails.length === 0) {
  lines.push("_None — no hard budget misses or render errors this run._");
} else {
  lines.push(
    "> Console-error findings are **per-shot observations** — a React hydration warning can be " +
      "intermittent, so the exact width column reflects which shot caught it, not a width-specific bug. " +
      "The route + error sample is the signal. Overflow is deterministic; CLS carries the dev caveat above.",
  );
  lines.push("");
  lines.push("| Route | State | Width | What broke |");
  lines.push("|---|---|---|---|");
  for (const r of fails) {
    const broke =
      r.status === "error"
        ? `error: ${(r.pageError ?? "").slice(0, 80)}`
        : budgetsFor(r)
            .filter((b) => HARD_KEYS.has(b.key) && b.verdict === "fail")
            .map((b) => `${b.label}=${b.value}`)
            .join("; ");
    lines.push(`| \`${r.routeId}\` | ${r.state} | ${r.width}px | ${broke} |`);
  }
}
lines.push("");
const skips = run.results.filter((r) => r.status === "skipped");
if (skips.length) {
  lines.push("## Skipped (no fixture / not reachable)");
  lines.push("");
  const seen = new Set<string>();
  for (const r of skips) {
    const k = `${r.routeId}:${r.state}`;
    if (seen.has(k)) continue;
    seen.add(k);
    lines.push(`- \`${r.routeId}\` · ${r.state} — ${r.skipReason ?? "n/a"}`);
  }
  lines.push("");
}
lines.push("---");
lines.push("");
lines.push(
  "_Regenerate: `npx tsx scripts/qa-auth-bootstrap.ts && npx playwright test --config playwright.qa.config.ts && npx tsx scripts/qa-report.ts`._",
);
lines.push("");
writeFileSync(INDEX_MD, lines.join("\n"));

// ── PRODUCT_DEBT auto-block ───────────────────────────────────────────────────────────────────
// Group hard fails by (routeId, budgetKey) → one debt row each, listing states + widths.
interface Grp {
  routeId: string;
  path: string;
  key: string;
  label: string;
  where: Set<string>;
  values: Set<string>;
  detail: Set<string>;
}
const groups = new Map<string, Grp>();
function grp(gk: string, r: ShotResult, key: string, label: string): Grp {
  const g = groups.get(gk) ?? {
    routeId: r.routeId,
    path: r.path,
    key,
    label,
    where: new Set(),
    values: new Set(),
    detail: new Set(),
  };
  groups.set(gk, g);
  return g;
}
for (const r of run.results) {
  if (r.status === "error") {
    const g = grp(
      `${r.routeId}:render-error`,
      r,
      "render-error",
      "Render error",
    );
    g.where.add(`${r.state}@${r.width}`);
    g.values.add((r.pageError ?? "error").slice(0, 60));
    continue;
  }
  for (const b of budgetsFor(r)) {
    if (!HARD_KEYS.has(b.key) || b.verdict !== "fail") continue;
    const g = grp(`${r.routeId}:${b.key}`, r, b.key, b.label);
    g.where.add(`${r.state}@${r.width}`);
    g.values.add(b.value);
    // For console/pageerror, attach a short sample so the founder knows what the error is.
    if (b.key === "console" && r.consoleSamples[0])
      g.detail.add(r.consoleSamples[0].slice(0, 70));
    if (b.key === "pageerror" && r.pageError)
      g.detail.add(r.pageError.slice(0, 70));
  }
}
// S1 = truly broken (dead page / uncaught error / bad status). Console/hydration warnings and
// layout budgets (overflow/CLS) are S2 — real, but the page still renders.
const severityFor = (key: string): string =>
  key === "render-error" || key === "pageerror" || key === "http" ? "S1" : "S2";

const debtRows: string[] = [];
let n = 1;
for (const g of groups.values()) {
  const where = [...g.where].sort().join(", ");
  const vals = [...g.values].join(" / ");
  const detail = g.detail.size ? ` — ${[...g.detail].join("; ")}` : "";
  const note = `QA-01 mechanical${detail}; screenshot in docs/qa/QA-01/`;
  debtRows.push(
    `| QA-${n} | \`${g.path}\` | ${g.label} miss (${vals}) at ${where} | ${severityFor(g.key)} | QA | OPEN | ${note} |`,
  );
  n++;
}

const block = [
  AUTO_START,
  `<!-- ${debtRows.length} row(s) from QA-01 run ${run.generatedAt} -->`,
  ...(debtRows.length
    ? debtRows
    : ["<!-- No hard budget misses this run. -->"]),
  AUTO_END,
].join("\n");

let debt = readFileSync(PRODUCT_DEBT, "utf8");
if (debt.includes(AUTO_START) && debt.includes(AUTO_END)) {
  debt = debt.replace(
    new RegExp(`${escapeRe(AUTO_START)}[\\s\\S]*?${escapeRe(AUTO_END)}`),
    block,
  );
} else {
  // Insert the auto-block just before the Changelog line (or append).
  const marker = "**Changelog:**";
  const idx = debt.indexOf(marker);
  const injected =
    "\n### QA-01 auto-filed (mechanical) rows\n\n" +
    "> Regenerated each QA-01 run. Broken states only (hard budget misses); advisory LCP/tap not filed.\n\n" +
    block +
    "\n\n";
  debt =
    idx === -1
      ? debt + injected
      : debt.slice(0, idx) + injected + debt.slice(idx);
}
writeFileSync(PRODUCT_DEBT, debt);

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// eslint-disable-next-line no-console
console.log(
  `QA-01 report → ${INDEX_MD}\n` +
    `  verdicts: PASS ${byVerdict.PASS} · ADV ${byVerdict.ADVISORY} · FAIL ${byVerdict.FAIL} · SKIP ${byVerdict.SKIP} · ERR ${byVerdict.ERROR}\n` +
    `  PRODUCT_DEBT auto-rows: ${debtRows.length}`,
);
